---
stages:
  - build
  - build-image
  - deploy

.stage_image_tag:
  variables:
    REGEX: "master-.*"
    IMAGE_VERSION: master-$CI_COMMIT_SHORT_SHA
  only:
    - master

.prod_image_tag:
  variables:
    REGEX: "tag-.*"
    IMAGE_VERSION: tag-$CI_COMMIT_TAG
  only:
    - tags

.build:
  stage: build
  image: node:10
  script:
    - yarn install
    - yarn build
    - tar -czvf ./build.tar.gz dist
  artifacts:
    expire_in: 7 days
    paths:
    - build.tar.gz
  tags:
    - docker

.image-build:
  stage: build-image
  script:
    - tar zxvf build.tar.gz -C ./
    - docker-compose build
    - docker-compose push
    - docker-compose down --rmi all
    - hub-tool tags:cleanup --path pet-projects/ronin --regexp ${REGEX} --count 5
  tags:
    - docker-engine

.deploy:
  variables:
    IMAGE_VERSION: ${CI_COMMIT_SHORT_SHA}
  stage: deploy
  image: docker-hub.2gis.ru/2gis-io/k8s-handle:latest
  script:
    - k8s-handle deploy --section ${CI_ENVIRONMENT_NAME} --sync-mode true
  tags:
    - 2gis
    - docker
  only:
    - master

build-stage-app:
  extends: .build
  variables:
    VUE_APP_ROOT_API: "https://samurai-dev.k8s.2gis.dev/api"
  only:
    - branches

build-prod-app:
  extends: .build
  variables:
    VUE_APP_ROOT_API: "https://samurai.k8s.2gis.dev/api"
  only:
    - tags

build-stage-image:
  extends:
    - .image-build
    - .stage_image_tag

build-prod-image:
  extends:
    - .image-build
    - .prod_image_tag

deploy-staging:
  environment:
    name: staging
    url: "http://kicktest.k8s.2gis.dev"
  extends:
    - .deploy
    - .stage_image_tag

deploy-prod:
  environment:
    name: production
    url: "http://kickstarter.k8s.2gis.dev"
  extends:
    - .deploy
    - .prod_image_tag
