---
common:
  k8s_master_uri: https://master.k8s.2gis.dev:6443
  k8s_token: "{{ env='K8S_TOKEN' }}"
  k8s_namespace: pet-projects

  app_port: 80

  replicas_count: 1
  image_path: docker-hub.2gis.ru/pet-projects/ronin
  image_version: "{{ env='IMAGE_VERSION' }}"

  requests_cpu: 30m
  limits_cpu: 100m
  requests_memory: 32M
  limits_memory: 64M

  ssl_enforce: "true"

  kubectl:
  - template: deployment.yaml.j2
  - template: service.yaml.j2

staging:
  app_name: ronin-dev
  ssl_domains: "ronin"

production:
  app_name: ronin
  ssl_domains: "kickstarter"
